const dataPrices = [
  {
    planId: "500",
    networkId: "1",
    networkName: "MTN",
    dataVolume: "500MB",
    price: "125",
    resellerPrice: "117.5",
    validity: "30 days",
  },
  {
    planId: "1000",
    networkId: "1",
    networkName: "MTN",
    dataVolume: "1GB",
    price: "250",
    resellerPrice: "235",
    validity: "30 days",
  },
  {
    planId: "2000",
    networkId: "1",
    networkName: "MTN",
    dataVolume: "2GB",
    price: "500",
    resellerPrice: "470",
    validity: "30 days",
  },
  {
    planId: "3000",
    networkId: "1",
    networkName: "MTN",
    dataVolume: "3GB",
    price: "750",
    resellerPrice: "705",
    validity: "30 days",
  },
  {
    planId: "5000",
    networkId: "1",
    networkName: "MTN",
    dataVolume: "5GB",
    price: "1250",
    resellerPrice: "1175",
    validity: "30 days",
  },
  {
    planId: "10000",
    networkId: "1",
    networkName: "MTN",
    dataVolume: "10GB",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  {
    planId: "667",
    networkId: "2",
    networkName: "GLO",
    dataVolume: "10GB",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
];
export default dataPrices;
