const dataPrices = [
  {
    planId: "1",
    networkId: "1",
    networkName: "MTN",
    dataVolume: "500MB SME",
    price: "125",
    resellerPrice: "117.5",
    validity: "30 days",
  },
  {
    planId: "2",
    networkId: "1",
    networkName: "MTN",
    dataVolume: "1GB SME",
    price: "250",
    resellerPrice: "235",
    validity: "30 days",
  },
  {
    planId: "3",
    networkId: "1",
    networkName: "MTN",
    dataVolume: "2GB SME",
    price: "500",
    resellerPrice: "470",
    validity: "30 days",
  },
  {
    planId: "4",
    networkId: "1",
    networkName: "MTN",
    dataVolume: "3GB SME",
    price: "750",
    resellerPrice: "705",
    validity: "30 days",
  },
  {
    planId: "5",
    networkId: "1",
    networkName: "MTN",
    dataVolume: "5GB SME",
    price: "1250",
    resellerPrice: "1175",
    validity: "30 days",
  },
  {
    planId: "6",
    networkId: "1",
    networkName: "MTN",
    dataVolume: "500MB CG",
    price: "125",
    resellerPrice: "117.5",
    validity: "30 days",
  },
  {
    planId: "7",
    networkId: "1",
    networkName: "MTN",
    dataVolume: "1GB CG",
    price: "250",
    resellerPrice: "235",
    validity: "30 days",
  },
  {
    planId: "8",
    networkId: "1",
    networkName: "MTN",
    dataVolume: "2GB CG",
    price: "500",
    resellerPrice: "470",
    validity: "30 days",
  },
  {
    planId: "9",
    networkId: "1",
    networkName: "MTN",
    dataVolume: "3GB CG",
    price: "750",
    resellerPrice: "705",
    validity: "30 days",
  },
  {
    planId: "10",
    networkId: "1",
    networkName: "MTN",
    dataVolume: "5GB CG",
    price: "1250",
    resellerPrice: "1175",
    validity: "30 days",
  },
  {
    planId: "11",
    networkId: "1",
    networkName: "MTN",
    dataVolume: "10GB CG",
    price: "2600",
    resellerPrice: "2580",
    validity: "30 days",
  },
  {
    planId: "12",
    networkId: "1",
    networkName: "MTN",
    dataVolume: "15GB CG",
    price: "2800",
    resellerPrice: "2760",
    validity: "30 days",
  },
  {
    planId: "13",
    networkId: "1",
    networkName: "MTN",
    dataVolume: "20GB CG",
    price: "5200",
    resellerPrice: "5150",
    validity: "30 days",
  },
  // GLO
  {
    planId: "101",
    networkId: "2",
    networkName: "GLO",
    dataVolume: "1.05GB CG",
    price: "500",
    resellerPrice: "450",
    validity: "30 days",
  },
  {
    planId: "102",
    networkId: "2",
    networkName: "GLO",
    dataVolume: "2.5GB CG",
    price: "900",
    resellerPrice: "880",
    validity: "30 days",
  },
  {
    planId: "103",
    networkId: "2",
    networkName: "GLO",
    dataVolume: "4.1GB CG",
    price: "1300",
    resellerPrice: "1250",
    validity: "30 days",
  },
  {
    planId: "104",
    networkId: "2",
    networkName: "GLO",
    dataVolume: "5.8GB CG",
    price: "1750",
    resellerPrice: "2350",
    validity: "30 days",
  },
  {
    planId: "105",
    networkId: "2",
    networkName: "GLO",
    dataVolume: "7.7GB CG",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  {
    planId: "106",
    networkId: "2",
    networkName: "GLO",
    dataVolume: "10GB CG",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  {
    planId: "107",
    networkId: "2",
    networkName: "GLO",
    dataVolume: "13.25GB CG",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  {
    planId: "108",
    networkId: "2",
    networkName: "GLO",
    dataVolume: "18.25GB CG",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  {
    planId: "109",
    networkId: "2",
    networkName: "GLO",
    dataVolume: "29.5GB CG",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  {
    planId: "110",
    networkId: "2",
    networkName: "GLO",
    dataVolume: "50GB CG",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  {
    planId: "111",
    networkId: "2",
    networkName: "GLO",
    dataVolume: "93GB CG",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  // AIRTEL
  {
    planId: "201",
    networkId: "3",
    networkName: "AIRTEL",
    dataVolume: "100MB CG",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  {
    planId: "202",
    networkId: "3",
    networkName: "AIRTEL",
    dataVolume: "500MB CG",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  {
    planId: "203",
    networkId: "3",
    networkName: "AIRTEL",
    dataVolume: "1GB CG",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  {
    planId: "204",
    networkId: "3",
    networkName: "AIRTEL",
    dataVolume: "2GB CG",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  {
    planId: "205",
    networkId: "3",
    networkName: "AIRTEL",
    dataVolume: "5GB CG",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  {
    planId: "206",
    networkId: "3",
    networkName: "AIRTEL",
    dataVolume: "10GB CG",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  {
    planId: "207",
    networkId: "3",
    networkName: "AIRTEL",
    dataVolume: "15GB CG",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  {
    planId: "208",
    networkId: "3",
    networkName: "AIRTEL",
    dataVolume: "20GB CG",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  // 9MOBILE
  {
    planId: "301",
    networkId: "4",
    networkName: "9MOBILE",
    dataVolume: "650MB GIFTING",
    price: "2500",
    resellerPrice: "2350",
    validity: "1 day",
  },
  {
    planId: "302",
    networkId: "4",
    networkName: "9MOBILE",
    dataVolume: "1GB GIFTING",
    price: "2500",
    resellerPrice: "2350",
    validity: "1 day",
  },
  {
    planId: "303",
    networkId: "4",
    networkName: "9MOBILE",
    dataVolume: "500MB GIFTING",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  {
    planId: "304",
    networkId: "4",
    networkName: "9MOBILE",
    dataVolume: "2GB GIFTING",
    price: "2500",
    resellerPrice: "2350",
    validity: "5 days",
  },
  {
    planId: "305",
    networkId: "4",
    networkName: "9MOBILE",
    dataVolume: "1.5GB GIFTING",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  {
    planId: "306",
    networkId: "4",
    networkName: "9MOBILE",
    dataVolume: "2GB GIFTING",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  {
    planId: "307",
    networkId: "4",
    networkName: "9MOBILE",
    dataVolume: "3GB GIFTING",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  {
    planId: "308",
    networkId: "4",
    networkName: "9MOBILE",
    dataVolume: "4.5GB GIFTING",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  {
    planId: "310",
    networkId: "4",
    networkName: "9MOBILE",
    dataVolume: "11GB GIFTING",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  {
    planId: "311",
    networkId: "4",
    networkName: "9MOBILE",
    dataVolume: "15GB GIFTING",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  {
    planId: "312",
    networkId: "4",
    networkName: "9MOBILE",
    dataVolume: "40GB GIFTING",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
  {
    planId: "313",
    networkId: "4",
    networkName: "9MOBILE",
    dataVolume: "75GB GIFTING",
    price: "2500",
    resellerPrice: "2350",
    validity: "30 days",
  },
];
export default dataPrices;
